### ISSUE TITLE
TFRPM01 RPM report zeros after I2C disconection and recovery

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/PX4-Autopilot#31]
The pcf8583 reports zeros after the interruption of the I²C bus, recovery is possible only by restarting the driver.

**Comment by roman-dvorak** [comment]
I think that this issue could solve also #

**Comment by slimonslimon** [comment]
okey, if i m albe to detect that device is disconected, i will improve the driver to detect disconection and  do reconection of device.

**Comment by slimonslimon** [comment]
i will improve this next week (before next flight), i will conect rpm sensor to my device.

**Comment by kaklik** [comment]
That seems to be resolved already.
